import "./globals.scss";
import { Space_Mono } from "next/font/google";
import Header from "../components/Header";
import Footer from "../components/Footer";

const space_Mono = Space_Mono({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Quiz AI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={space_Mono.className}>
        <div className="h-screen bg-slate-900 text-slate-100">
          <div className="h-screen max-w-3xl mx-auto flex flex-col">
            <Header />
            {children}
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
